# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tW8RzKjK9gTkzrM5y6gs9W-EqzEaWmX
"""

# 📢 Disclaimer
print("📢 Disclaimer: Crypto investments are risky! Always do your own research (DYOR). This is not financial advice.\n")

# 🤖 Bot Intro
print("👋 Hey there! I’m CryptoBuddy — your friendly AI sidekick for crypto advice! Let’s find you a smart and sustainable coin to invest in 🚀🌱")
print("Ask me anything like: 'Which crypto is trending?' or 'What's the most eco-friendly coin?'")
print("Type 'exit' to end chat.\n")

# 📊 Sample Crypto Data
crypto_db = {
    "Bitcoin": {
        "price_trend": "rising",
        "market_cap": "high",
        "energy_use": "high",
        "sustainability_score": 3/10
    },
    "Ethereum": {
        "price_trend": "stable",
        "market_cap": "high",
        "energy_use": "medium",
        "sustainability_score": 6/10
    },
    "Cardano": {
        "price_trend": "rising",
        "market_cap": "medium",
        "energy_use": "low",
        "sustainability_score": 8/10
    }
}

# 💡 Chatbot Logic
def get_recommendation(user_query):
    query = user_query.lower()

    if "sustainable" in query:
        recommend = max(crypto_db, key=lambda x: crypto_db[x]["sustainability_score"])
        return f"🌱 Go for {recommend}! It's eco-friendly and built for long-term impact."

    elif "trending" in query or "growth" in query:
        trending = [name for name, data in crypto_db.items()
                    if data["price_trend"] == "rising" and data["market_cap"] in ["high", "medium"]]
        return f"🚀 For long-term growth, check out: {', '.join(trending)}!"

    elif "buy" in query:
        best = None
        for name, data in crypto_db.items():
            if data["price_trend"] == "rising" and data["market_cap"] == "high":
                best = name
                break
        return f"💡 Consider buying {best} — strong market cap and trending upwards!"

    elif "bitcoin" in query:
        return "⚡ Bitcoin is booming, but its energy use is very high. Trade wisely!"

    else:
        return "🤔 I'm not sure about that. Try asking about trends, sustainability, or what to buy."

# 💬 Start Chat
def start_chat():
    while True:
        user_input = input("You: ")
        if user_input.lower() == "exit":
            print("CryptoBuddy: 🫡 Stay smart, invest wise! Bye!")
            break
        response = get_recommendation(user_input)
        print(f"CryptoBuddy: {response}\n")

start_chat()